name: CI/CD Pipeline

on:
  push:
    branches: [ "feature/docker-setup", "main" ]

jobs:
  build-test-scan-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image for Scanning
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: g2yoan/banking-app:test

      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@0.29.0
        with:
          image-ref: 'g2yoan/banking-app:test'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Build and Push Final Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            g2yoan/banking-app:v1
            g2yoan/banking-app:latest